### ISSUE TITLE
Negative Balance 

### ISSUE THREAD

**Issue by BasedJumper** [alt-coin-xao/alloy#1]
The wallet displays negative balances

**Comment by glencjones** [comment]
Confirmed issue with  walletd, as discussed in chat.  simplewallet is not affected by this bug.

**Comment by glencjones** [comment]
Not a complete fix, this has resolved 64 bits at the network layer (RPC), but we may have another source for the -ve returned via walletd.  Possibly unspent Transactions.

So two bugs that might cause the -1 return for walletd.  One down another to go.

As stated previously this does not appear as an issue in simplewallet.

**Comment by glencjones** [comment]
Will raise seperate ticket to fix additional transaction pending I believe. Causing incorrect balance in walletd, simplewallet not affected.
